services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env
    volumes:
      - redis:/bitnami/redis/data

volumes:
  db:
    driver: local
  redis:
    driver: local
